config/routes.rb
Rails.application.routes.draw do
  resources :productions, only: [:index, :new, :create, :show]
  root 'productions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_production.rb
class DailyProduction < ApplicationRecord
	has_many :hourly_productions
	has_and_belongs_to_many :inverters

	validates :energy_production, :presence => true
	validates :energy_production, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

	validates :date, :presence => true
end

app/models/hourly_production.rb
class HourlyProduction < ApplicationRecord
	belongs_to :daily_production
	belongs_to :inverter

	validates :energy_production, :presence => true
	validates :energy_production, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

	validates :datetime, :presence => true

end

app/models/inverter.rb
class Inverter < ApplicationRecord
	has_many :hourly_productions
	has_and_belongs_to_many :daily_productions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/productions_controller.rb
require 'csv'
require 'set'

class ProductionsController < ApplicationController
	def index
		@daily_productions = DailyProduction.includes("inverters").all
	end

	def new
	end

	def create
		@daily_production = DailyProduction.new(energy_production: 0)
		inverters_id = Set[]
		inverters = []
		hourly_productions = []
		datetime = nil

		CSV.foreach(params[:file].path, headers:true) do |row|
			inverter_id = row["identifier"].to_i
			inverters_id.add(inverter_id)
			datetime = DateTime.strptime(row["datetime"], "%d/%m/%y %H:%M")
			hourly_productions << {
				inverter_id: inverter_id,
				datetime: datetime,
				energy_production: row["energy"].to_i
			}
			@daily_production.energy_production += row["energy"].to_i
		end
		@daily_production.date = datetime.to_date
		ActiveRecord::Base.transaction do
			for inverter_id in inverters_id do
				inverters << Inverter.find_or_create_by(id: inverter_id)
			end
			@daily_production.hourly_productions.build(hourly_productions)
			@daily_production.save
			@daily_production.inverters << inverters
		end

		redirect_to production_path(@daily_production.id)
	end

	def show
		@daily_production = DailyProduction.includes("inverters", "hourly_productions").find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/productions_helper.rb
module ProductionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestEpices</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/productions/index.html.erb
<h1>List of Daily productions</h1>
<div class="row">
	<div class="col-12">
		<%= link_to 'Upload csv', new_production_path, class: 'btn btn-primary' %>
	</div>
	<div class="col-12">
		<table class="table">
			<thead>
				<tr>
				<th scope="col">#</th>
				<th scope="col">Date</th>
				<th scope="col">Energy</th>
				<th scope="col">Inverter</th>
				<th scope="col"></th>
				</tr>
			</thead>
			<tbody>
				<% @daily_productions.each do |daily_production| %>
					<tr>
					<th scope="row"><%= daily_production.id %></th>
					<td><%= daily_production.date %></td>
					<td><%= daily_production.energy_production %></td>
					<td><%= daily_production.inverters.map(&:id).join(", ") %></td>
					<td><%= link_to 'See more', production_path(daily_production.id), class: 'btn btn-secondary' %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/productions/new.html.erb
<h1>Upload CSV</h1>
<div class="row">
	<div class="col-12 mb-3">
		<%= link_to 'Return to daily production list', productions_path, class: 'btn btn-secondary' %>
	</div>
	<div class="col-12">
		<%= form_with(url: productions_path, multipart: true) do %>
			<div class="form-group">
				<%= file_field_tag :file, accept: ".csv" %>
			</div>
			<%= submit_tag("Import", class: "btn btn-primary") %>
		<% end %>
	</div>
</div>

app/views/productions/show.html.erb
<h1>Daily production <%= @daily_production.id %></h1>
<div class="row">
	<div class="col-12">
	<%= link_to 'Return to list', productions_path, class: 'btn btn-primary' %>
	</div>
	<div class="col-4">
		Date: <%= @daily_production.date %>
	</div>
	<div class="col-4">
		Total energy: <%= @daily_production.energy_production %>
	</div>
	<div class="col-4">
		<%= @daily_production.inverters.map(&:id).join(", ") %>
	</div>
	<div class="col-12">
		<table class="table">
			<thead>
				<tr>
				<th scope="col">#</th>
				<th scope="col">Date</th>
				<th scope="col">Energy</th>
				<th scope="col">Inverter</th>
				</tr>
			</thead>
			<tbody>
				<% @daily_production.hourly_productions.each do |hourly_production| %>
					<tr>
					<th scope="row"><%= hourly_production.id %></th>
					<td><%= hourly_production.datetime %></td>
					<td><%= hourly_production.energy_production %></td>
					<td><%= hourly_production.inverter_id %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>